### ISSUE TITLE
add-pkcs8 command fails if part of post-boot-asadmin-commands

### ISSUE THREAD

**Issue by ratcashdev** [payara/docker-payaraserver-full#93]
I am trying to generate a new (self-signed) certificate for my container. The dockerfile looks like this:
```
FROM payara/server-full:5.184
...
# customize the server-config
COPY --chown=payara:payara docker-stuff/post-boot-asadmin-commands ${POSTBOOT_COMMANDS}

...
# refresh the certificate (currently expired)
COPY ./docker-stuff/openssl-csr.cnf ./
RUN openssl req -config openssl-csr.cnf -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```

The asadmin add-pkcs8 command works fine if started from the command line, but fails if it is part of the `post-boot-asadmin-commands` file.
```
add-pkcs8 --destalias snake-cert --priv-key-path /opt/payara/key.pem  --cert-chain-path /opt/payara/cert.pem
set configs.config.server-config.network-config.protocols.protocol.http-listener-2.ssl.cert-nickname=snake-cert 
set server.network-config.network-listeners.network-listener.http-listener-2.enabled=false
set server.network-config.network-listeners.network-listener.http-listener-2.enabled=true
```

The error in the logs is the following:
```
[#|2019-07-30T19:04:42.045+0000|INFO|Payara 5.184||_ThreadID=1;_ThreadName=main;_TimeMillis=1564513482045;_LevelValue=800;|
  Reading in commandments from /opt/payara/config/post-boot-commands.asadmin|#]

[#|2019-07-30T19:04:42.045+0000|INFO|Payara 5.184||_ThreadID=1;_ThreadName=main;_TimeMillis=1564513482045;_LevelValue=800;|
  Running command: add-pkcs8 --destalias snake-cert --priv-key-path /opt/payara/key.pem  --cert-chain-path /opt/payara/cert.pem|#]

[#|2019-07-30T19:04:42.046+0000|INFO|Payara 5.184||_ThreadID=1;_ThreadName=main;_TimeMillis=1564513482046;_LevelValue=800;|
  Exception while executing command.|#]

[#|2019-07-30T19:04:42.047+0000|SEVERE|Payara 5.184||_ThreadID=1;_ThreadName=main;_TimeMillis=1564513482047;_LevelValue=1000;|
  org.glassfish.api.admin.CommandException: Command lookup failed for command add-pkcs8
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.getParameters(CommandExecutorImpl.java:106)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:166)
        at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.run(CommandExecutorImpl.java:96)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.runCommand(GlassFishMain.java:240)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.doBootCommands(GlassFishMain.java:300)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:109)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:54)
```

it works, if executed manually, from within the container:
```
payara@701ce232119b:~$ asadmin add-pkcs8 --destalias snake-cert --priv-key-path /opt/payara/key.pem  --cert-chain-path /opt/payara/cert.pem
/opt/payara/appserver/glassfish/domains/production/config/keystore.jks
Private key with alias [snake-cert] added to keystore /opt/payara/appserver/glassfish/domains/production/config/keystore.jks.
Command add-pkcs8 executed successfully.
```

**Comment by agois-inc** [comment]
Hello.  First, thank you for taking a look at this.  

Has there been any headway?  Hopefully it doesn't get lost in the weeds with everything else in the works.  

Thanks!

**Comment by agois-inc** [comment]
This looks like it's related:
https://github.com/payara/Payara/issues/4010

**Comment by johnmanko** [comment]
Does commit https://github.com/payara/docker-payaraserver-full/commit/0240ca5c8d2c1dfc2e8a0549469dfd2895f72a6d fix this issue?

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived.
